version: '3'
services:
  dd-agent: # Add this section
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=us5.datadoghq.com
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true # Collect logs from all containers
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - datadog_network
  # goodconfig:
  #   build:
  #     context: ./goodconfig
  #     args:
  #       DD_API_KEY: ${DD_API_KEY}
  #   image: goodconfig
  #   container_name: goodconfig
  #   ports:
  #     - '8080:80'
  #   environment:
  #     - DD_API_KEY=${DD_API_KEY}
  #   networks:
  #     - datadog_network
  # misconfig1:
  #   build:
  #     context: ./misconfig1
  #     args:
  #       DD_API_KEY: ${DD_API_KEY}
  #   image: misconfig1
  #   container_name: misconfig1
  #   ports:
  #     - '8081:80'
  #   environment:
  #     - DD_API_KEY=${DD_API_KEY}
  #   networks:
  #     - datadog_network
  # misconfig2:
  #   build:
  #     context: ./misconfig2
  #     args:
  #       DD_API_KEY: ${DD_API_KEY}
  #   image: misconfig2
  #   container_name: misconfig2
  #   ports:
  #     - '8082:80'
  #   environment:
  #     - DD_API_KEY=${DD_API_KEY}
  #   networks:
  #     - datadog_network
  # misconfig3:
  #   image: misconfig3
  #   container_name: misconfig3
  #   build:
  #     context: ./misconfig3
  #     args:
  #       DD_API_KEY: ${DD_API_KEY}
  #   ports:
  #     - '8083:80'
  #   environment:
  #     - DD_API_KEY=${DD_API_KEY}
  #   depends_on:
  #     - database
  #   networks:
  #     - datadog_network
  database:
    image: postgres:13
    container_name: database
    environment:
      - POSTGRES_USER=datadog
      - POSTGRES_PASSWORD=datadog
      - POSTGRES_DB=mydatabase
    ports:
      - '5432:5432'
    networks:
      - datadog_network
  misconfig4:
    image: misconfig4
    container_name: misconfig4
    build:
      context: ./misconfig4
      args:
        DD_API_KEY: ${DD_API_KEY}
        DD_GIT_COMMIT_SHA: $(git rev-parse HEAD)
        DD_GIT_REPOSITORY_URL: $(git config --get remote.origin.url)
    ports:
      - '8084:80'
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_AGENT_HOST=dd-agent
    depends_on:
      - database
      - dd-agent
    networks:
      - datadog_network
    labels:
      com.datadoghq.ad.logs: >-
        [
          {
            "source": "python", 
            "service": "misconfig4",
            "log_processing_rules": {
              "type": "multi_line"
              "name": "pattern_multiline"
              "pattern": "\\d{4}-\\d{2}-\\d{2}"
              "include_at_match": true
            }
          }
        ]

networks:
  datadog_network:
    driver: bridge
